<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="projectSierraModel" nsURI="http://www.example.org/projectSierraModel"
    nsPrefix="projectSierraModel">
  <eClassifiers xsi:type="ecore:EClass" name="Capabilitty" eSuperTypes="#//SpecializableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="includes" upperBound="-1"
        eType="#//Capabilitty" eOpposite="#//Capabilitty/isIncludedIn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isIncludedIn" eType="#//Capabilitty"
        eOpposite="#//Capabilitty/includes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" eType="#//Capabilitty"
        eOpposite="#//Capabilitty/isExtendedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isExtendedBy" upperBound="-1"
        eType="#//Capabilitty" eOpposite="#//Capabilitty/extends"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isImplementedBy" lowerBound="1"
        eType="#//Chain" eOpposite="#//Chain/implements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="involves" lowerBound="1"
        upperBound="-1" eType="#//InvolveableElement" eOpposite="#//InvolveableElement/isInvolvedIn"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpecializableElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specializes" eType="#//SpecializableElement"
        eOpposite="#//SpecializableElement/isSpecializedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isSpecializedBy" eType="#//SpecializableElement"
        eOpposite="#//SpecializableElement/specializes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainableElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" upperBound="-1"
        eType="#//ContainableElement" eOpposite="#//ContainableElement/isContainedIn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isContainedIn" eType="#//ContainableElement"
        eOpposite="#//ContainableElement/contains"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containableElements" upperBound="-1"
        eType="#//ContainableElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specializableElements"
        upperBound="-1" eType="#//SpecializableElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="performingElements" upperBound="-1"
        eType="#//PerformingElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExchangeElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exchange" eSuperTypes="#//ContainableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendsTo" lowerBound="1"
        eType="#//ExchangeElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receivesFrom" lowerBound="1"
        eType="#//ExchangeElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conveys" eType="#//Item"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//ExchangeElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasPort" eType="#//Port"
        eOpposite="#//Port/isPortOf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasInput" eType="#//Input"
        eOpposite="#//Input/isInputOf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasOuput" eType="#//Ouput"
        eOpposite="#//Ouput/isOuputOf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isPerformedBy" lowerBound="1"
        eType="#//PerformingElement" eOpposite="#//PerformingElement/performs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" eSuperTypes="#//ExchangeElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isPortOf" eType="#//Function"
        eOpposite="#//Function/hasPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Input" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isInputOf" eType="#//Function"
        eOpposite="#//Function/hasInput"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ouput" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isOuputOf" eType="#//Function"
        eOpposite="#//Function/hasOuput"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PerformingElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="performs" upperBound="-1"
        eType="#//Function" eOpposite="#//Function/isPerformedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exchangeElements" upperBound="-1"
        eType="#//ExchangeElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvolveableElement" abstract="true"
      eSuperTypes="#//SpecializableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isInvolvedIn" lowerBound="1"
        eType="#//Capabilitty" eOpposite="#//Capabilitty/involves"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//InvolveableElement #//PerformingElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//InvolveableElement #//PerformingElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Chain" eSuperTypes="#//ContainableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implements" eType="#//Capabilitty"
        eOpposite="#//Capabilitty/isImplementedBy"/>
  </eClassifiers>
</ecore:EPackage>
