<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="projectSierraModel" nsURI="http://www.example.org/projectSierraModel"
    nsPrefix="projectSierraModel">
  <eClassifiers xsi:type="ecore:EClass" name="SpecializableElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specializes" upperBound="-1"
        eType="#//SpecializableElement" transient="true" eOpposite="#//SpecializableElement/isSpcecializedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isSpcecializedBy" upperBound="-1"
        eType="#//SpecializableElement" transient="true" eOpposite="#//SpecializableElement/specializes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainableElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" upperBound="-1"
        eType="#//ContainableElement" eOpposite="#//ContainableElement/containedIn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedIn" eType="#//ContainableElement"
        eOpposite="#//ContainableElement/contains"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasExpression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isExpressedIn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Capability" eSuperTypes="#//SpecializableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="involves" upperBound="-1"
        eType="#//InvolvableElement" eOpposite="#//InvolvableElement/involvedIn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includes" upperBound="-1"
        eType="#//Capability" eOpposite="#//Capability/isIncludedIn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isIncludedIn" upperBound="-1"
        eType="#//Capability" eOpposite="#//Capability/includes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" upperBound="-1"
        eType="#//Capability" eOpposite="#//Capability/isExtendedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isExtendedBy" upperBound="-1"
        eType="#//Capability" eOpposite="#//Capability/extends"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isSupportedBy" eType="#//System"
        eOpposite="#//System/support"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implements" eType="#//Chain"
        eOpposite="#//Chain/isImplementedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvolvableElement" abstract="true" eSuperTypes="#//SpecializableElement #//PerformingElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="involvedIn" upperBound="-1"
        eType="#//Capability" eOpposite="#//Capability/involves"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//InvolvableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//InvolvableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//ContainableElement #//PerformingElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="support" eType="#//Capability"
        eOpposite="#//Capability/isSupportedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PerformingElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="performs" upperBound="-1"
        eType="#//Function" eOpposite="#//Function/isPerformedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExchangingElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendsTo" eType="#//Exchange"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//ExchangingElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasPort" eType="#//Port"
        eOpposite="#//Port/isPortOf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasInput" eType="#//Input"
        eOpposite="#//Input/isInputOf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasOutput" eType="#//Output"
        eOpposite="#//Output/isOutputOf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isPerformedBy" upperBound="-1"
        eType="#//PerformingElement" eOpposite="#//PerformingElement/performs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conveys" eType="#//Exchange"
        eOpposite="#//Exchange/isConveyedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chain" eSuperTypes="#//ContainableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isImplementedBy" eType="#//Capability"
        eOpposite="#//Capability/implements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" eSuperTypes="#//ExchangingElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isPortOf" eType="#//Function"
        eOpposite="#//Function/hasPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Input" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isInputOf" eType="#//Function"
        eOpposite="#//Function/hasInput"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Output" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isOutputOf" eType="#//Function"
        eOpposite="#//Function/hasOutput"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exchange" eSuperTypes="#//ContainableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="receivesFrom" eType="#//ExchangingElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isConveyedBy" upperBound="-1"
        eType="#//Item" eOpposite="#//Item/conveys"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement" eSuperTypes="#//ContainableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasRationale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasConstraint" eType="#//Constraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="derives" eType="#//Requirement"
        eOpposite="#//Requirement/isDerivedFrom"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isDerivedFrom" eType="#//Requirement"
        eOpposite="#//Requirement/derives"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refines" eType="#//Requirement"
        eOpposite="#//Requirement/isRefinedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isRefinedBy" eType="#//Requirement"
        eOpposite="#//Requirement/refines"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specifies" eType="#//DesignElement"
        eOpposite="#//DesignElement/isSpecifiedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="justifies" eType="#//DesignElement"
        eOpposite="#//DesignElement/isJustifiedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DesignElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isSpecifiedBy" eType="#//Requirement"
        eOpposite="#//Requirement/specifies"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isJustifiedBy" eType="#//Requirement"
        eOpposite="#//Requirement/justifies"/>
  </eClassifiers>
</ecore:EPackage>
